package com.example.topquiz_kotlin.controler

import com.example.topquiz_kotlin.model.Question

/*
    Created by Edghi Makol on 16/04/21 at 21:22
*/

val snkListQuestion : List<Question> =
    listOf(
        Question("Comment s'appelle le titan de Eren en Japonais ?",
            listOf("Shingeki No Kyojin", "Kyojin Titan", "Shingetsu Bahamut", "Shingeki "),
        0),
        Question("Le type de lecteur ciblé par les studios d’edition varie en fonction des editeurs." +
                    "C’est l’exemple de <L'attaque des Titans> qui voit sa cible editoriale variée." +
                    "Qu’elles sont les deux types de mangas sous lequel Shingeki peut facilement se fondre ?",
            listOf("Shonen & Yaoi", "Seinen & Josei", "Shonen & Seinen", "Shonen & Josei"),
            2),
        Question("Donnez les noms des 3 murs du plus petit au plus grand dans lequel l’humanité se cache " +
                    "pour se proteger des Titans ? ",
            listOf("Mur Sina-Mur Rose-Mur Maria", "Mur Rose-Mur Sina-Mur Maria", "Mur Maria-Mur Sina-Mur Rose", "Mur Rose-Mur Maria-Mur Sina"),
            0),
        Question("De combien de mètres le Titan Colossal dépasse t’il le Mur Maria ?",
            listOf("5 m", "10 m", "15 m", "20 m"),
            1),
        Question("Au sein du bataillon d'exploration, quel est le grade de Livai Ackerman ?",
            listOf("Caporal-Chef", "Caporal-Major", "Lieutenant-Caporal", "Caporal"),
            0),
        Question("Comment s’appelle le liquide qui sert a la transmission du pouvoir de metarmorphose en Titan ?",
            listOf("Liquide Celebro-Spinale", "Liquide Cerebro-Spilale", "Liquide Cerebro-Spinale", "Liquide Celebro-Spilale"),
            2),
        Question("Quelle est la profession de l’homme dont l'auteur s’est inspiré pour créer le Chara-Design du Titan Cuirassé ?",
            listOf("Sprinteur", "Catcheur", "Forgeron", "Boxeur"),
            1),
        Question("C’est quoi le nom de l’opening 1 et de l’ending 2 de Shingeki no Kyojin ?",
            listOf("Guren No Yumiya & Great Escape", "Sasageyo & Call Your Name", "Jiyuu No Tsubasa & Utsukushiki Zankoku Na Sekai", "The Reluctant Heroes & DOA"),
            0),
        Question("Qui a construit les murs qui protège les Eldiens des Titans ?",
            listOf("Karl Fritz", "Les Mahrs", "Les Titans Primordiaux", "Ymir"),
            0),
        Question("Un Eldien est un natif de… ",
            listOf("L'ile du Paradis", "L'Empire Fritz", "L'Empire Eldienne", "L'Empire d'Eldia"),
            3),
        Question("D’où est ce que le Roi Karl Fritz s’est t’il inspiré pour nommer les différents Murs sur l’ile du paradis ?",
            listOf("De ses 3 filles", "Des 3 soeurs d'Ymir Fritz", "Des 3 premieres detenteuses de l'Originel", "Des 3 filles d'Ymir Fritz"),
            3),
        Question("Pourquoi le 145e Roi d’Eldia fit le vœu de renoncer à utiliser le pouvoir du TITAN ORIGINEL ?",
            listOf("Pour proteger son peuple de l'exterieur", "Pour garder l'equilibre du Monde", "Par pitie des peuples exterieurs", "Pour s’assurer que le titan en question ne soit jamais utilisé a de mauvaises fins"),
            3),
        Question("Combien d’année ce sont Ecoulée entre la destruction du Mur dans le district de Shiganshina et la conquete de " +
                    "celle si par le bataillon d’exploration ? ",
            listOf("3 ans", "4 ans", "5 ans", "6 ans"),
            2),
        Question("Quel est le nom complet de la premiere victime D’Armin en titan ?",
            listOf("Bertolt Hoover", "Erwin Smith", "Marco Bott", "Reiner Braun"),
            0),
        Question(
            "Après la Bataille ou fut mort le Major Erwin, a combien s’éleve le nombre de Survivant au sein du bataillon d’exploration ?",
            listOf("9", "8", "10", "7"),
            0),
        Question("Le district de Trost est rataché a quel Mur ?",
            listOf("Le Mur Maria", "Le Mur Rose", "Le Mur Sina", "Le Mur Shiganshina"),
            1),
        Question("Combien de Titan Primordiaux sont impliqués a la bataille de Shiganshina ?",
            listOf("5", "4", "3", "6"),
            0),
        Question("Combien de jeunes en tout faisaient partie de la 104e Brigade d’entrainement ?",
            listOf("216", "217", "218", "219"),
            2),
        Question("Quel est l’autre nom donner au Bataillon d’exploration ?",
            listOf("Rodeurs des Murs", "Bataillon de la Liberte", "Chasseurs de Titans", "Corps de Reconnaissance"),
            3),
        Question("Comment s’appelle les ailes qui se trouvent sur l’insigne du bataillon d’explorations ? ",
            listOf("Les Ailes de la Foi", "Les Ailes de l'Exploration", "Les Ailes de la Liberté", "Les Ailes du Courage"),
            2),
        Question("Après la mort du Major Erwin Smith qui prend le commandement du bataillon d’exploration ?",
            listOf("Armin Arlert", "Hansi Zoe", "Livai Ackerman", "Eren Jager"),
            1),
        Question("Quel est le nom complet de l’assassin de BEAN & SAWNEY ?",
            listOf("Jean Kirstein", "Annie Leonhart", "Reiner Braun", "Aucune des propositions"),
            1),
        Question("Un detenteur de Titan Primordial a une longevite de combien d'annees ?",
            listOf("7 ans", "20 ans", "13 ans", "16 ans"),
            2),
        Question("A quel age Eren obtient son Titan Primordial ?",
            listOf("9 ans", "10 ans", "11 ans", "12 ans"),
            1),
        Question("Qui est l'auteur de Shingeki No Kyojin ?",
            listOf("Masashi Kishimoto", "Eichiro Oda", "Hiro Mashima", "Hajime Isayama"),
            3),
        Question("Comment s'appelle la Reine de l'ile du Paradis ?",
            listOf("Historia Fritz", "Historia Reiss", "Christa Reiss", "Christa Fritz"),
            1),
        Question("En quelle annee est sortie Shingeki No Kyojin ?",
            listOf("1999", "2006", "2009", "2013"),
            2),
        Question("Combien de Titans possede Eren ?",
            listOf("3", "1", "2", "4"),
            0),
        Question("Comment s'appelle le soldat qui a sauve Eren et Mikasa lors de la premiere apparition du " +
                    "titan colossal ?",
            listOf("Dieter", "Moses", "Waltz", "Hannes"),
            3)
    )

val narutoShippListQuestion : List<Question> =
    listOf(
        Question("Quel age a Naruto lorsqu'il sauve le village de l'attaque de l'Akatsuki ?",
        listOf("16 ans", "17 ans", "18 ans", "On a pas dit dans l'anime"),
        0),
        Question("Quel est le surnom de Shisui ?",
        listOf("Shisui de l'ombre", "Shisui du mirage", "Shisui des corbeaux", "Shisui le sage"),
        1),
        Question("En quelle creature Kabuto pretendait-il s'etre transformer a la 4e Grande Guerre Ninja ?",
        listOf("Phoenix", "Cameleon", "Dragon", "Serpent Immortel"),
        2),
        Question("Quelle est la particularite de l'eventail des Uchiwa ?",
        listOf("Creer des tempetes", "Boulverser la meteo", "Repousser l'adversaire", "Renvoyer des techniques"),
        3),
        Question("Qui etait le premier des Kages ressuscite a etre scelle a la 4e Grande Guerre Ninja ?",
        listOf("Kazekage", "Mizukage", "Raikage", "Hokage"),
        0),
        Question("Quel est le nom japonais de la technique qui a valu le titre d'eclair jaune a Minato ?",
        listOf("Kaiten Souda", "Hiraichin", "Chidori", "Raiton"),
        1),
        Question("Quelles sont les techniques que Kakashi ne peut copier?",
        listOf("Les techniques interdites", "Les techniques a grande dose de chakra", "Les techniques hereditaires", "Il peut tout copier !"),
        2),
        Question("Quelle est la signification de Hokage ?",
        listOf("Dirigeant de feu", "Protecteur de feu", "Sauveur de feu", "Ombre de feu"),
        3),
        Question("Quel est l'appelation du premier Hokage en japonais ?",
        listOf("Shodai Hokage", "Sandaime Hokage", "Godaime Hokage", "Rokudaime Hokage"),
        0),
        Question("Quel est le surnom d'Hashirama Senju ?",
        listOf("Pere des Shinobi", "Dieu des Shinobi", "Roi des Shinobi", "Il n'avait pas de surnom !"),
        1)
    )

val mhaListQuestion : List<Question> =
    listOf(
        Question("Quel est le surnom du heros ?",
        listOf("Deku", "Izuku", "Haiku", "Midoriya"),
        0),
        Question("Quel est le nom de code d'Ochako Uraraka ?",
        listOf("Gravity", "Ochako", "Uravity", "Gravity 0"),
        2),
        Question("Quel est l'Alter de Mei Hatsume du departement d'invention ?",
        listOf("Cible", "Zoom", "Creation", "Invention"),
        1),
        Question("Pourquoi Izuku se fait-il appeler Deku ?",
        listOf("Parce que Katsuki l'appelle ainsi", "Parce qu'Ochako trouve ce surnom encourageant",
            "Parce qu'il l'a invente en tant que nom de code", "Parce que ca veut dire courage en japonais"),
        1),
        Question("Quel est le peche mignon de Minoru Mineta ?",
        listOf("La bouffe", "Dormir", "Les filles", "Le dessin"),
        2),
        Question("Comment Shouto Todoroki a t-il recu sa cicatrice ?",
        listOf("Son pere l'a brule avec son Alter", "Il s'est brule lui-meme en decouvrant son Alter", "Sa mere l'a brule avec de l'eau bouillante",
        "Il a saute dans le feu"),
        2),
        Question("Quel est la soi-disant nationalite de Yuga ?",
        listOf("Japonaise", "Italienne", "Chinoise", "Francaise"),
        3),
        Question("Quel eleve de la seconde A possede le meme nom de code que son Alter ?",
        listOf("Denki", "Momo", "Mezo", "Kyoka"),
        3),
        Question("Quelle est la particularite de Denki Kaminari ?",
        listOf("Son Alter le rend debile", "Son Alter est surpuissant", "Il se teint les cheveux", "Il est secretement amoureux de Kyoka"),
        0),
        Question("Comment s'appelle l'attaque speciale de Tenya Lida ?",
        listOf("Engine", "Ingenium", "Recipro Burst", "Il n'en a pas"),
        2),
        Question("Quelle est la condition pour que l'Alter de Momo fonctionne ?",
        listOf("Elle doit avoir parfaitement l'objet en tete", "Elle doit connaitre la composition de l'objet", "Elle doit fermer les yeux", "Elle doit etre dehors"),
        1),
        Question("Quand est-il plus facile a Fumikage de controler Dark Shadow ?",
        listOf("Quand il fait sombre", "Quand il est en pleine forme", "Quand il fait jour", "Quand il est fatigue"),
        2),
        Question("Qui est le professeur principal de la seconde B ?",
        listOf("Midnight", "Eraser Head", "Vlad King", "Snipe"),
        2)
    )

val opListQuestion : List<Question> =
    listOf(
        Question("Qui est le premier adversaire que Luffy a affronte ?",
        listOf("Zorro", "Alvida", "Arlong", "Koby"),
        1),
        Question("A qui appartenait le chapeau de Luffy avant qu'on le lui donne ?",
        listOf("Garp", "Roger", "Ace", "Shanks"),
        3),
        Question("Comment Shanks a t-il perdu son bras ?",
        listOf("Pendant un duel contre Mihawk", "En voulant sauver Luffy d'un brigand", "Contre Barbe Noire", "En voulant sauver Luffy d'un monstre marin"),
        3),
        Question("Quel est le veritable nom de Barbe Noire ?",
        listOf("Marshall D. Teach", "Edward D. Teach", "Teach D. Marchall", "Teach D. Edward"),
        0),
        Question("Qui a tue Barbe Blanche ?",
        listOf("Ace", "Barbe Noire", "Akainu", "Il est mort d'une maladie"),
        1),
        Question("Qu'est ce que le Haki des Rois ?",
        listOf("Cela permet de voir dans le futur", "Cela permet de rendre inconscients ses adversaires", "Cela permet de propulser sa force vers un adversaire",
        "Cela permet de se proteger par une armure d'energie"),
        2),
        Question("Quelle est la prime de Captain Kid ?",
        listOf("200.000", "200.000.000", "315.000.000", "350.000.000"),
        2),
        Question("Qui est le second de Kaido ?",
        listOf("Jack", "Kid", "King", "Oden"),
        2),
        Question("Qui etait le rival de Roger ?",
        listOf("Teach", "Barbe Blanche", "Kaido", "Xebeck"),
        1),
        Question("Quel est le fruit de Doflamingo ?",
        listOf("Pika pika no mi", "Gomu gomu no mi", "Ito ito no mi", "Mira mira no mi"),
        2),
        Question("Qui sont les ennemis du gouvernement ?",
        listOf("Les CP9", "Les CP0", "Les pirates", "Les corsaires"),
        2),
        Question("Qui est le heros de la Marine ?",
        listOf("Garp", "Akainu", "Sengoku", "Aokiji"),
        0),
        Question("Qui sont le GERMA66 ?",
        listOf("Les rois de North Blue", "Des Tenryuubito", "Une association du gouvernement", "Les Vinsmoke"),
        3),
        Question("Ou se cache le One Piece ?",
        listOf("A Raftel", "A Onigashima", "Dans la mer", "On ne sait pas"),
        0),
        Question("Quand a-t-on vu le Gear Fourth pour la premiere fois ?",
        listOf("Dans les flashback de Luffy avec Rayleigt", "Pendant l'entrainement de Luffy", "Contre Katakuri", "Contre Doflamingo"),
        0),
        Question("Comment s'appelle le dernier sabre de Zorro ?",
        listOf("Shisui", "Enma", "Wado Ichimonji", "Nidai Kitetsu"),
        1),
        Question("Le fruit de Luffy est...",
        listOf("Un Logia", "Un paramecia", "Un zoan", "Un zoan antique"),
        1),
        Question("Qui est Marco ?",
        listOf("Le meilleur ami de Ace", "Le fils de Barbe Blanche", "Un compagnon de Roger", "Le second de Barbe Blanche"),
        3),
        Question("Parmi tous ces mots lequel n'est pas une attaque de Luffy ?",
        listOf("Jet gatling", "Hado Elbow", "Kong organe", "Jet pistol"),
        1),
        Question("Parmi tous ces noms lequel n'a jamais ete amiral ?",
        listOf("Garp", "Aokiji", "Kisaru", "Fujitora"),
        0),
        Question("Quelle est la particularite de Big Mom ?",
        listOf("Elle est grande", "Elle a une force exceptionnelle", "Elle peut interagir avec les ames", "Elle peut tout manger"),
        2)
    )